workfloworchestrator/orchestrator-core-gui

src/components/inputForms/UserInputForm.scss, src/lib/uniforms-surfnet/src/DividerField.tsx, src/lib/uniforms-surfnet/src/index.ts
Added Label with value from backend + Form dividers
=> Added Label with value from backend + Form dividers

src/components/subscriptionDetail/Renderers.tsx, src/locale/en.ts
Update the field Name to Product Name in the context of the subscription detail page. And fixes a broken link.
=> Fix product name and link

src/components/subscriptionDetail/Renderers.tsx
=> Fix linting

src/custom-surf/components/LabelledFilter.tsx, src/custom-surf/pages/Prefixes.tsx
- replaced FilterDropDown with EuiComboBox
- added filter for root prefix
Filter settings are not yet remembered, which was a comment in the task (1268).
=> feat: filter LIR prefixes

src/custom-surf/pages/Prefixes.scss, src/custom-surf/pages/Prefixes.tsx, src/custom-surf/plugins/RenderExternalLinks.tsx
This pull request adds some improvements to the LIR prefix table.
- clicking on prefix opens window in new tab
- prefixes with state "free" will not be filtered out when a search filtering is applied
- the root prefix filter dropdown now contains all available prefixes selected
=> LIR-prefixes-table-features

src/api/axios.ts, src/components/modals/components/FavoritePortSelector.tsx, src/components/modals/components/ServicePortSelector.tsx, src/components/subscriptionDetail/Renderers.tsx, src/components/subscriptionDetail/SubscriptionDetail.tsx, src/custom-surf/components/LabelledFilter.tsx, src/custom-surf/components/subscriptionDetail/TopologyDiagram.tsx, src/forms/Builder.tsx
- clean up old console.logs that don't seem necessary.
- fix old todo.
=> Fix parameter values not being filled in of action messages

src/components/subscriptionDetail/SubscriptionDetails.tsx
Add permissions for sync button
=> Set in sync permissions

.github/workflows/scheduled-build.yml, .github/workflows/test-standalone.yml, .github/workflows/test-surf.yml
Add a workflow that builds and tests the project every 2 weeks and sends the outcome to Slack.
=> Add scheduled build

src/components/subscriptionDetail/Renderers.tsx, src/components/subscriptionDetail/SubscriptionDetail.tsx, src/contextProviders/ConfirmationDialogProvider/index.tsx, src/contextProviders/globalContextProviders.tsx, src/pages/SubscriptionDetailPage.tsx
- Create context provider for confirm dialog so it can be used anywhere without needing to pass things through components.
=> Fix actions not showing for subscriptions in subscription list

.env.local.example, README.md
documented a work around for problems with websockets whilst runnign teh dev server
=> documented a work around for problems with websockets

src/custom-surf/api/index.ts, src/custom-surf/pages/ServiceTicketDetail.tsx
- improve log item actions render.
=> CIM: add abort api call and hookup to abort button

src/components/inputForms/UserInputForm.tsx, src/components/inputForms/UserInputFormWizard.tsx, src/custom-surf/api/index.ts, src/custom-surf/components/cim/OpenForm.tsx, src/custom-surf/components/cim/ServiceTicketDetailImpactedObjects.tsx, src/custom-surf/manifest.json, src/custom-surf/pages/CreateServiceTicket.tsx, src/custom-surf/pages/ServiceTicketDetail.tsx, src/custom-surf/pages/ServiceTicketOpen.tsx, src/custom-surf/pages/ServiceTickets.tsx, src/custom-surf/pages/ServiceTicketsStyling.ts, src/custom-surf/types.ts, src/locale/en.ts, src/pages/App.tsx
* Change UserInputForm to allow overriding the text and color of previous/next buttons, and to show a dialog for the previous button
* Make the order of custompages consistent
* Cim serviceticket Open : Add ServiceTicketOpen page and OpenForm component
* Cim serviceticket Create: Change `title` to `title_nl`
* Cim serviceticket Detail: fix Opening button requiredState
* Cim servicetickets: adjust column widths
=> ServiceTicket Open (cim#10)

src/pages/ModifySubscription.tsx, src/pages/NewProcess.tsx, src/pages/NewTask.tsx, src/pages/ProcessDetail.tsx, src/pages/TerminateSubscription.tsx
- Change form submit in process detail to stay on page instead of redirect
=> Redirect workflow submit to process detail

src/pages/ProcessDetail.tsx, src/pages/ProcessDetailStyling.ts
- add fixed top menu when scrolling past actions on the page
=> Add auto scrolling to last finished step in process details

CHANGELOG.md
- `#157` Redirect workflow submit to process detail
- `#158` Add auto scrolling to last finished step in process details, a button to turn auto scrolling off or on and add fixed top menu when scrolling past actions on the page.
Surf specific:
- `#155` cim: Check if impacted service has subscription id before calling api
- `#156` cim: Add html parser to form summary field for email examples
=> Update changelog to version v10.5.0 with PR 155, 156, 157 and 158

src/custom-surf/components/subscriptionDetail/TopologyDiagram.tsx
- change sap.port_subscription_id to sap.port.owner_subscription_id.
- check if the sap has another sap instead of a port.
=> Fix topology diagram

src/custom-surf/components/subscriptionDetail/TopologyDiagram.tsx
=> Show details for the cloud in l2vpn in the diagram

CHANGELOG.md, package.json, src/custom-surf/components/subscriptionDetail/TopologyDiagram.tsx, yarn.lock
- only use sap.sap for the port owner subscription id, prefixes are in sap instead of sap.sap.
- also add wolk explanation inside buildIP.
=> Fix IPS and IPBGP topology diagram

CHANGELOG.md, src/pages/SubscriptionsStyling.ts
=> Fix styling

src/custom-surf/Utils.ts, src/custom-surf/api/index.ts, src/custom-surf/components/cim/BackgroundJobLogs.tsx, src/custom-surf/components/cim/OpenForm.tsx, src/custom-surf/pages/CloseServiceTicket.tsx, src/custom-surf/pages/OpenServiceTicket.tsx, src/custom-surf/pages/ServiceTicketDetail.tsx, src/custom-surf/pages/ServiceTicketMails.tsx, src/custom-surf/pages/ServiceTickets.tsx, src/custom-surf/pages/UpdateServiceTicket.tsx, src/lib/uniforms-surfnet/src/TimestampField.tsx, src/utils/Time.ts
Uniforms:
* Add `src/Utils/Time` for converting to/from UTC timestamp and localized `Moment`
* Add `disabled` property to `TimestampField` and use timestamp/moment conversion functions
Surf-Specific (CIM):
* Consistent formatting for dates/times, handle empty endDate
* Show ticket name in form header
=> cim#38 Date and tim changes

src/components/subscriptionDetail/SubscriptionDetails.tsx, src/locale/en.ts, src/pages/Processes.tsx, src/pages/Tasks.tsx, src/stories/data/processes/statuses.json, src/utils/types.ts, src/validations/Processes.ts
* Fix several Processes page errors by adding process status [RESUMED](https://github.com/workfloworchestrator/orchestrator-core/issues/242) and set correct task url (orchestrator#1664)
* Fix retrying/aborting a failed Task raising TypeError (orchestrator-client#54)
=> Process status resumed and fixes

src/components/tables/Subscriptions.tsx, src/components/tables/cellRenderers.tsx, src/locale/en.ts, src/pages/Subscriptions.tsx, src/utils/types.ts
- Adds a new default hidden column `references` to the Subscriptiontables
- Formats cell from the subscription metadata field
=> Add column for subscription references

src/pages/ProcessDetail.tsx, src/utils/types.ts
- null type is object, so correctly added it as type and check if product is not false.
=> Fix product id check in process detail

src/custom-surf/components/inputForms/SplitPrefix.tsx
Added logic that the minimal prefix length as defined by business rules is applied to the values of the prefix length dropdown
=> Improved the selectable prefixlengths in dropdown
