src/pages/Processes.tsx
- change updateRunningProcesses to set showtables back to true after one milisecond.
- also change it to update only when the list changes, otherwise it infinite loops for some reason.
=> Fix tables not reloading in processes list with websockets

src/components/ProcessStateDetails.tsx, src/components/failedTaskBanner/index.tsx, src/components/tables/NwaTable.tsx, src/pages/ProcessDetail.tsx, src/utils/types.ts, src/utils/useHttpIntervalFallback.ts, src/websocketService/useRunningProcesses/RunningProcessesContext.tsx, src/websocketService/useRunningProcesses/index.ts, src/websocketService/useWebsocket.ts
- change ProcessDetail to use RunningProcessesContext and remove old websocket logic.
- update RunningProcessesContext to keep track of completed processes.
- update failedTaskBanner to initially fetch failed processes with http request.
- move productName and customerName in ProcessDetail to the state and remove CustomProcessWithDetails.
- change RunningProcessesContext processes type to `WsProcessV2`.
Depend on orchestrator core update: https://github.com/workfloworchestrator/orchestrator-core/pull/74
=> Update websocket process detail

src/components/subscriptionDetail/SubscriptionDetails.tsx
see issue 20.
If unresolved (because CRM might be unavailable) the UUID was shown. 
The field is now hidden if unresolved (i.e. equal to the UUID).
=> do not show customer name if not resolved

src/components/subscriptionDetail/SubscriptionDetail.scss, src/components/subscriptionDetail/TabbedSection.tsx, src/components/subscriptionDetail/templates/ServiceConfiguration.tsx
Implemented a few changes as requested after the initial tabview release:
- remove heading from rendered blocks in tabview
- display instance ID in configuration tabs
- add margin to tabview sections for clarity
=> Tabview changes

src/components/Header.scss, src/components/Header.tsx, src/components/engineStatusBanner/EngineStatusBanner.scss, src/components/engineStatusBanner/index.tsx, src/components/failedTaskBanner/index.tsx, src/components/tables/NwaTable.tsx, src/contextProviders/engineSettingsProvider/index.tsx, src/contextProviders/globalContextProviders.tsx, src/contextProviders/runningProcessesProvider/index.tsx, src/pages/App.tsx, src/pages/ProcessDetail.tsx, src/pages/Settings.tsx
- add contextProviders folder.
- add globalContextProviders to easily add global providers without nesting directly in app.tsx.
- add context provider for engine settings.
- replace places that need engine settings to use engineSettingsProvider.
- change the engine settings banner in header to a component `engineStatusBanner`.
- move RunningProcessesContext to contextProviders folder.
=> Change engine status data to come from websocket with http as fallback

src/components/EditProduct.tsx, src/components/ProductBlock.tsx, src/components/ProductBlocks.tsx, src/components/Products.tsx, src/components/SubscriptionValidation.tsx, src/components/inputForms/UserInputForm.tsx, src/components/subscriptionDetail/Renderers.tsx, src/contextProviders/ConfirmationDialogProvider/index.tsx, src/pages/ProcessDetail.tsx, src/pages/Processes.tsx, src/pages/Subscriptions.tsx, src/pages/Tasks.tsx
components had their own confirmation dialog which is now changed to a contextprovider which all components can use.
=> Change components that use ConfirmationDialog to use ConfirmationDialogContext provider

src/components/Navigation.scss
fixed it with adding `!important` to the `sync` class, don't know if we should fix it directly in `.euitoast` class from elastic ui.
fixes the sync from looking like this:
to:
=> Fix sync toast position that made the page jump up and down

src/components/inputForms/UserInputForm.tsx, src/lib/uniforms-surfnet/src/RadioField.tsx
One of our ESnet Orchestrated services is "Physical Connection Service", which allows network engineers to create & manage subscriptions that configure physical interfaces on network devices.
A recent feature request was to make the configuration more granular for LAG interfaces: allowing configuration for the admin-state (shutdown true/false) for individual LAG member ports, as well as the LAG interface itself.
I couldn't find a way to use the `en.ts` or `i18n` translations to map a custom, dynamic label to a form field.
For example:
Say there is a LAG interface "lag-2", which aggregates interfaces "1/1/c5/1" and "1/1/c6/1" on device "ALU-1".
One could make the _value_ associated to a radio button or drop-down select field look like this in the rendered form:
```
● connection: …
```
=> Allow user to specify 'label' for dynamic form field label creation

src/api/index.ts
- without the slash it redirects to http
=> Fix run new task

src/components/inputForms/UserInputForm.tsx
- first check if translation exists before using the prop label
=> Fix form input translations

CHANGELOG.md, src/lib/uniforms-surfnet/src/SummaryField.tsx, src/pages/ProcessDetail.tsx
- fix summaryfield by checking if row is string.
=> Scroll to last step in process details when page is loaded except when process is done

src/custom-surf/components/FormHeader.tsx, src/custom-surf/pages/CloseServiceTicket.tsx, src/custom-surf/pages/CreateServiceTicket.tsx, src/custom-surf/pages/OpenServiceTicket.tsx, src/custom-surf/pages/UpdateServiceTicket.tsx
The Explain rerenders `OpenServiceTicket` component and also rerenders the form, moving you to the start of the form.
=> Fix explain in the form sending you back to the start

src/custom-surf/api/index.ts
Make the CIM host for local development a variable so that we can also run a dev server on k8s. On k8s stuff will not work when we hardcode the hostname to localhost.
=> add variable for local dev cim host

src/custom-surf/api/index.ts, src/custom-surf/components/cim/OpenForm.tsx, src/custom-surf/pages/ServiceTicketDetail.tsx, src/custom-surf/pages/ServiceTickets.tsx, src/custom-surf/types.ts
* Use available ticket transitions to decide which buttons to show, and change ticket state by applying transitions
* Renamed `ServiceTicketProcessState.INITIAL` to `ServiceTicketProcessState.NEW`
* Added `ServiceTicketTransition` enum
* Removed `ServiceTicketState` enum
=> cim#18 Use transition instead of process_state as much as possible

src/custom-surf/api/index.ts, src/custom-surf/components/cim/BackgroundJobLogs.tsx, src/custom-surf/components/cim/ImpactedObjects.tsx, src/custom-surf/components/cim/OpenForm.tsx, src/custom-surf/pages/ServiceTicketDetail.tsx, src/custom-surf/types.ts, src/locale/en.ts
Surf specific changes for `cim#44`:
* Add feature to recover a failed inform job (extended `ServiceTicketLog` and `BackgroundJobLog`)
* Enhance background logs (show more context, make sortable)
* Don't show a popup when a service ticket refresh fails
=> Cim#44 Allow recovering ticket inform job

src/api/index.ts, src/locale/en.ts, src/pages/Settings.tsx
* Use new endpoint `/cache-names` to retrieve possible caches to delete
* Display the number of deleted cache keys
=> Get cache options from API, display delete count

src/custom-surf/api/index.ts, src/custom-surf/pages/ServiceTickets.tsx, src/locale/en.ts
Surf specific (cim)
* Add button to delete tickets stuck in state `NEW` when there is no active background job
* Sort tickets table by last update time (desc) & hide aborted/closed tickets in the default filter
* Translation fixes
=> CIM fixes/usability

src/pages/ProcessDetail.tsx
The detail page stops updating when there is a form so it doesn't reset.
If the form is handled, the detail page does update for other instances.
This is mostly caused by httpFallback that triggers every 3 seconds, tried checking if the data even needs to be updated, but somehow the `process` isn't ever the same as the `processInstance` it is updated with at line 84
=> Fix form resetting when process updates

src/components/subscriptionDetail/templates/ServiceConfiguration.tsx
Join resource-type value array to a string, fixes displaying multiple values
=> Fix displaying multiple resource-type values

src/components/ProcessStateDetailsStyling.ts
This PR adds CSS styling to pretty-print dry-run results in the process tab, ie:
=> feat: add styling to pretty print dry run in the process state

src/api/index.ts, src/contextProviders/engineSettingsProvider/index.tsx, src/locale/en.ts, src/pages/Settings.tsx, src/utils/types.ts
Uses `/api/settings/worker-status` endpoint and shows info in the settings page
=> Add card for worker status to settings page

src/pages/App.tsx
While the order of `importedModules`is guaranteed, the order of `importedModules.map(...)` isn't. 
As a result the app will _sometimes_ define (and thus match) `<Route>` components in a wrong order.
The added `.sort()` call ensures a consistent order.
=> Consistent custompage route order

src/api/index.ts, src/custom-surf/api/index.ts, src/custom-surf/pages/ServiceTicketDetail.tsx, src/custom-surf/pages/ServiceTicketMails.tsx, src/locale/en.ts
CIM changes:
* fix serviceticket detail showing 'unexpected error' popup instead of a 'Ticket not found' page
* don't fetch ticket transitions when there is no ticket
* add "back" button on Last Sent Emails page
=> CIM: 404 handling, back button

src/components/modals/ProcessTableCellModal.tsx, src/components/tables/cellRenderers.tsx, src/env.ts, src/locale/en.ts, src/locale/i18n.ts, src/pages/App.tsx
For Processes which can modify/touch multiple Subscriptions (a rare and non-standard case), the ProcessTable component's default rendering style is to join an `EuiFlexGroup` of `Link`s with a forward slash (`/`).
This works for one or two `<Link>` components, but quickly breaks with more than three.
This MR moves any group of cell data with more than 3 items into a scrollable `Modal` component for legibility.
=> Add modal to process table

src/pages/Subscriptions.tsx
This PR deleted some TSV examples which won't work. Removing this lines, will bring focus to the relevant section above, explaning the need to use "" whenever a string contains "-", "_", or ","
=> deleted TSV explanation which is not correct

src/utils/policy.ts
=> Rewrite /auth to /opa in OIDC URL with a more specific match

src/pages/ProcessDetail.tsx, src/utils/types.ts
Resolved an issue where inconsistent `product_id` types caused the UI to stop refreshing. Adjusted type checking to handle both string and object forms of product_id.
=> Fix UI Refresh Issue due to product_id Type Variance

src/custom-example/uniforms/AutoFieldLoader.tsx, src/env.ts, src/websocketService/index.ts
the latest `react-use-websocket` has this feature built in and actually does something with the pong. but it's dependent on react 18 https://www.npmjs.com/package/react-use-websocket/v/4.5.0#heartbeat
- add divider into custom-example auto field loader
=> Add ping pong mechanic to websocket service to keep connection healthy

src/components/subscriptionDetail/templates/ServiceConfiguration.tsx
this breaks subscription detail page with tabs showing only `-`
=> Remove in_use_by_relations from the subscription detail page

src/custom-surf/components/inputForms/AutocompleteStyling.ts
Remove `position: absolute` from the Autocomplete component's css so that it renders at the correct place.
Also increased color contrast between text and background 
Fixes https://git.ia.surfsara.nl/netdev/automation/projects/orchestrator-client/-/issues/60
=> Fix position of Autocomplete component

src/lib/uniforms-surfnet/src/SelectField.tsx
In case of a modify flow we need to send the removal of a value to the backend. Before this change, it meant the value changes to `undefined`. However, `undefined` won't get sent to the backend (and backend does not allow a value to be `undefined`.
In case the value becomes `undefined` by clicking on the X on the select field, we change this value to `null`
Unfortunately ts-ignore is needed since onChange does not allow `null` as value.
=> SelectField - Converts undefined to null

src/custom-surf/uniforms/AutoFieldLoader.tsx, src/lib/uniforms-surfnet/src/SubscriptionField.tsx, src/lib/uniforms-surfnet/src/index.ts, src/lib/uniforms-surfnet/src/logic/CustomerField.tsx, src/locale/en.ts
we are renaming organisation to customer in the backend, so made some changes to make V1 compatible for new and old backend versions.
- new CustomerId field to work with `CustomerId` type in backend.
- update SubscriptionField to work with customer as wel as organisation properties.
=> Add CustomerId field
